export const clockSkins = {
  full: {
    default: {
      animationSpeed: .4,
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: true,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,
      numbersDisplay: true,
      moonDisplay: true,
      sunDisplay: true,
      dayNightRingDisplay: true,

      dial: 'bg-white shadow-lg',
      hand: 'text-black',
      ntzHand: 'text-white',
      title: 'text-slate-400',

      mustachesEquinox: 'text-slate-400',
      mustachesSummerSunrise: 'text-slate-400',
      mustachesWinterSunrise: 'text-slate-400',
      mustachesWinterSunset: 'text-slate-400',
      mustachesSummerSunset: 'text-slate-400',

      dotsMultipleOf90: 'bg-slate-800',
      dotsMultipleOf30: 'bg-slate-300',
      dotsMultipleOf10: 'bg-slate-300',

      numbersMultipleOf90: 'text-slate-800 font-black',
      numbersMultipleOf30: 'text-slate-400 font-extrabold',
      numbersMultipleOf10: 'text-slate-300 font-thin',
      
      dayNightRing: 'opacity-100',
    },
    hideClockGraduations: {
      dotsDisplay: false,
      numbersDisplay: false,
    },
    welcome: {
      context: {
        currentTime: new Date(new Date().setUTCHours(10, 0, 0, 0)),
        latitude: 42.42,
        longitude: 0,
      },
      animationSpeed: .5,
      descriptionText: "Découvrir une façon plus simple et plus logique de mesurer le temps qui passe dans une journée",
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: false,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,

      dotsMultipleOf90: 'bg-slate-800',
      dotsMultipleOf30: 'bg-slate-300',
      dotsMultipleOf10: 'bg-slate-300',

      numbersMultipleOf90: 'text-slate-800 font-black',
      numbersMultipleOf30: 'text-slate-400 font-extrabold',
      numbersMultipleOf10: 'text-slate-300 font-thin',
    },
    tutorial: [
      {
        context: {
          currentTime: new Date(1356085600000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'Je suis une horloge naturelle',
        descriptionText: "Je pointe à chaque instant en direction du soleil",
        animationSpeed: .8,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon unique aiguille",
        descriptionText: 'Tourne lentement, une seule fois par jour',
        animationSpeed: 8,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon cadran est gradué en 360°",
        descriptionText: 'Bye bye les 24 heures 60 minutes et 60 secondes',
        animationSpeed: 0.5,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        handDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-gray-300 font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-300',
        dotsMultipleOf10: 'bg-slate-300',
      },
      {
        context: {
          currentTime: new Date(1356091200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "180° est le véritable midi",
        descriptionText: 'Lorsque le soleil est au zénith',
        animationSpeed: 2,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-white font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-200',
        dotsMultipleOf10: 'bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1356134399000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "0° marque le vrai milieu de la nuit",
        descriptionText: "Lorsque le soleil est de l'autre côté de la Terre",
        animationSpeed: 2,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-white font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-200',
        dotsMultipleOf10: 'bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1356134400000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Les moustaches représentent le jour et la nuit",
        descriptionText: "En fonction de la saison et de la latitude",
        animationSpeed: 0.4,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        titleDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        handDisplay: false,
        mustachesEquinox: 'text-black',
        mustachesSummerSunrise: 'text-black',
        mustachesWinterSunrise: 'text-black',
        mustachesWinterSunset: 'text-black',
        mustachesSummerSunset: 'text-black',
      },
      {
        context: {
          currentTime: new Date(1340252400000 + 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'été...",
        descriptionText: "Le soleil se lève par ici",
        animationSpeed: 1.2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-cyan-dark',
        mustachesEquinox: 'text-slate-400',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1340307600000 - 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'été...",
        descriptionText: "Puis se couche par là",
        animationSpeed: 2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-cyan-dark',
        mustachesEquinox: 'text-slate-400',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1356161400000 + 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'hiver...",
        descriptionText: "Le soleil se lève ici",
        animationSpeed: 1,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-cyan-dark',
        mustachesEquinox: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1356193800000 - 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'hiver...",
        descriptionText: "Et se couche par là",
        animationSpeed: 2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-cyan-dark',
        mustachesEquinox: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Les jours d'équinoxes (seulement)",
        descriptionText: "La durée du jour est égale à celle de la nuit",
        animationSpeed: .8,
        handDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        mustachesEquinox: 'text-nt-yellow-dark',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesSummerSunset: 'text-slate-400',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'On ne dit plus "Quelle heure est-il ?"',
        descriptionText: 'Mais plutôt : "Où est le soleil dans le ciel ?"',
        animationSpeed: 2,
        handDisplay: false,
        dotsDisplay: true,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: true,
        mustachesEquinox: 'text-nt-yellow-dark',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesSummerSunset: 'text-slate-400',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000 + 1000 * 4 * 60 * 42),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'Le soleil est à 222°',
        descriptionText: '(par exemple)',
        animationSpeed: .3,
        handDisplay: true,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        mustachesEquinox: 'text-nt-yellow-dark',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesSummerSunset: 'text-slate-400',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000 + 1000 * 4 * 60 * 42),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'Les nombres du cadran ne sont pas essentiels...',
        descriptionText: "L'horloge naturelle est avant tout une expérience visuelle",
        animationSpeed: 2,
        mustachesDisplay: true,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Tutoriel terminé !",
        descriptionText: "Pour continuer, l'application a besoin de configurer une position géographique",
        dotsDisplay: true,
        handDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        sunDisplay: true,
      }
    ]
  }
}