export const clockSkins = {
  full: {
    default: {
      animationSpeed: 0.4,
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: true,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,
      numbersDisplay: true,
      moonDisplay: true,
      sunDisplay: true,
      dayNightRingDisplay: true,

      dial: 'bg-white shadow-lg',
      hand: 'text-black',
      ntzHand: 'text-white',
      title: 'text-slate-400',

      mustachesEquinox: 'text-slate-400',
      mustachesSummerSunrise: 'text-slate-400',
      mustachesWinterSunrise: 'text-slate-400',
      mustachesWinterSunset: 'text-slate-400',
      mustachesSummerSunset: 'text-slate-400',

      dotsMultipleOf90: 'bg-slate-800',
      dotsMultipleOf30: 'bg-slate-300',
      dotsMultipleOf10: 'bg-slate-300',

      numbersMultipleOf90: 'text-slate-800 font-black',
      numbersMultipleOf30: 'text-slate-400 font-extrabold',
      numbersMultipleOf10: 'text-slate-300 font-thin',
      
      dayNightRing: 'opacity-100',
    },
    simplifiedMode: {
      dotsDisplay: false,
      numbersDisplay: false,
      ntzDisplay: false,

      mustachesEquinox: 'text-slate-400/40',
      mustachesSummerSunrise: 'text-slate-400/40',
      mustachesWinterSunrise: 'text-slate-400/40',
      mustachesWinterSunset: 'text-slate-400/40',
      mustachesSummerSunset: 'text-slate-400/40',
    },
    welcome: {
      context: {
        currentTime: new Date(new Date().setUTCHours(10, 0, 0, 0)),
        latitude: 42.42,
        longitude: 0,
      },
      animationSpeed: .5,
      descriptionTextKey: "tutorials.clock.welcome.description",
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: false,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,

      dotsMultipleOf90: 'bg-slate-800',
      dotsMultipleOf30: 'bg-slate-300',
      dotsMultipleOf10: 'bg-slate-300',

      numbersMultipleOf90: 'text-slate-800 font-black',
      numbersMultipleOf30: 'text-slate-200 font-extrabold',
      numbersMultipleOf10: 'text-white font-thin',
    },
    tutorial: [
      {
        context: {
          currentTime: new Date(1356085600000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step1.title',
        descriptionTextKey: 'tutorials.clock.step1.description',
        animationSpeed: .8,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356085600000 + 1000*60*60*1),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step2.title',
        descriptionTextKey: 'tutorials.clock.step2.description',
        animationSpeed: 8,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step3.title',
        descriptionTextKey: 'tutorials.clock.step3.description',
        animationSpeed: 0.5,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        handDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-gray-300 font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-300',
        dotsMultipleOf10: 'bg-slate-300',
      },
      {
        context: {
          currentTime: new Date(1356091200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step4.title',
        descriptionTextKey: 'tutorials.clock.step4.description',
        animationSpeed: 2,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-white font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-200',
        dotsMultipleOf10: 'bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1356134399000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step5.title',
        descriptionTextKey: 'tutorials.clock.step5.description',
        animationSpeed: 2,
        handDisplay: true,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        numbersMultipleOf90: 'text-black font-black',
        numbersMultipleOf30: 'text-white font-extrabold',
        numbersMultipleOf10: 'text-white font-thin',
        dotsMultipleOf90: 'bg-black',
        dotsMultipleOf30: 'bg-slate-200',
        dotsMultipleOf10: 'bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1340252400000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step6.title',
        descriptionTextKey: 'tutorials.clock.step6.description',
        animationSpeed: 0.4,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        titleDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        handDisplay: false,
        mustachesEquinox: 'text-black',
        mustachesSummerSunrise: 'text-black',
        mustachesWinterSunrise: 'text-black',
        mustachesWinterSunset: 'text-black',
        mustachesSummerSunset: 'text-black',
      },
      {
        context: {
          currentTime: new Date(1340252760000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step7.title',
        descriptionTextKey: 'tutorials.clock.step7.description',
        animationSpeed: 1.2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-yellow-dark',
        mustachesEquinox: 'text-slate-200',
        mustachesWinterSunrise: 'text-slate-200',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-200',
      },
      {
        context: {
          currentTime: new Date(1340307120000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step8.title',
        descriptionTextKey: 'tutorials.clock.step8.description',
        animationSpeed: 2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-yellow-dark',
        mustachesEquinox: 'text-slate-200',
        mustachesWinterSunrise: 'text-slate-200',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-200',
      },
      {
        context: {
          currentTime: new Date(1356161760000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step9.title',
        descriptionTextKey: 'tutorials.clock.step9.description',
        animationSpeed: 1,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-yellow-dark',
        mustachesEquinox: 'text-slate-200',
        mustachesSummerSunrise: 'text-slate-200',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-200',
      },
      {
        context: {
          currentTime: new Date(1356193440000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step10.title',
        descriptionTextKey: 'tutorials.clock.step10.description',
        animationSpeed: 2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        hand: 'text-nt-yellow-dark',
        mustachesEquinox: 'text-slate-200',
        mustachesSummerSunrise: 'text-slate-200',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-200',
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step11.title',
        descriptionTextKey: 'tutorials.clock.step11.description',
        animationSpeed: .8,
        handDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: true,
        mustachesEquinox: 'text-nt-yellow-dark',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesSummerSunset: 'text-slate-400',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000 + 1000 * 4 * 60 * 42),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step12.title',
        descriptionTextKey: 'tutorials.clock.step12.description',
        animationSpeed: 2,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: true,
        mustachesDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1332331200000 + 1000 * 4 * 60 * 42),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step13.title',
        descriptionTextKey: 'tutorials.clock.step13.description',
        animationSpeed: .3,
        handDisplay: true,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        mustachesDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1332331200000 + 1000 * 4 * 60 * 42),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.step14.title',
        descriptionTextKey: 'tutorials.clock.step14.description',
        animationSpeed: 2,
        mustachesDisplay: true,
        handDisplay: true,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleTextKey: 'tutorials.clock.end.title',
        descriptionTextKey: 'tutorials.clock.end.description',
        dotsDisplay: true,
        handDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        sunDisplay: true,
      }
    ]
  }
}