export const skins = {
  full: {
    default: {
      animationSpeed: .4,
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: true,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,
      numbersDisplay: true,
      moonDisplay: false,
      sunDisplay: false,
      dayNightRingDisplay: true,
      dayNightBlurDisplay: false,

      dial: 'bg-white shadow-lg',
      hand: 'text-black',
      ntzHand: 'text-white',
      title: 'text-slate-400',

      mustachesEquinox: 'text-slate-400',
      mustachesSummerSunrise: 'text-slate-400',
      mustachesWinterSunrise: 'text-slate-400',
      mustachesWinterSunset: 'text-slate-400',
      mustachesSummerSunset: 'text-slate-400',

      dotsMultipleOf90: 'w-4 h-4 mt-1 bg-slate-800',
      dotsMultipleOf30: 'w-2 h-2 mt-2 bg-slate-300',
      dotsMultipleOf10: 'w-2 h-2 mt-2 bg-slate-300',

      numbersMultipleOf90: 'text-slate-800 font-black text-3xl',
      numbersMultipleOf30: 'text-slate-400 font-extrabold text-lg',
      numbersMultipleOf10: 'text-slate-300 font-thin text-lg',
      
      dayNightRing: 'opacity-100',
      dayNightBlur: 'opacity-100',
    },
    hideClockGraduations: {
      dotsDisplay: false,
      numbersDisplay: false,
    },
    showClockAnimations: {
      dayNightBlurDisplay: true,
      sunDisplay: true,
      moonDisplay: true,
    },
    welcome: {
      context: {
        currentTime: new Date(new Date().setUTCHours(10, 0, 0, 0)),
        latitude: 42.42,
        longitude: 0,
      },
      animationSpeed: .5,
      titleText: 'Bienvenue ici et maintenant',
      descriptionText: "Le Temps Naturel est une autre façon de mesurer le temps",
      mustachesDisplay: true,
      dialDisplay: true,
      handDisplay: true,
      ntzDisplay: true,
      titleDisplay: true,
      dotsDisplay: true,
      numbersDisplay: false,
      sunDisplay: false,

      mustachesEquinox: 'text-nt-yellow-light',
      mustachesSummerSunrise: 'text-nt-yellow-light',
      mustachesWinterSunrise: 'text-nt-yellow-light',
      mustachesWinterSunset: 'text-nt-yellow-light',
      mustachesSummerSunset: 'text-nt-yellow-light',

      dotsMultipleOf90: 'w-4 h-4 bg-black',
      dotsMultipleOf30: 'w-2 h-2 mt-1 bg-black ',
      dotsMultipleOf10: 'w-1 h-1 mt-2 bg-black',

      numbersMultipleOf90: 'text-slate-800 font-black text-3xl',
      numbersMultipleOf30: 'text-slate-400 font-extrabold text-lg',
      numbersMultipleOf10: 'text-slate-300 font-thin text-lg',
    },
    tutorial: [
      {
        context: {
          currentTime: new Date(1356085600000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'Je suis une horloge naturelle',
        descriptionText: "Je pointe à chaque instant en direction du soleil",
        animationSpeed: .8,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon unique aiguille",
        descriptionText: 'Tourne lentement, une seule fois par jour',
        animationSpeed: 8,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon cadran est gradué en 360°",
        descriptionText: 'Bye bye les 24 heures 60 minutes et 60 secondes',
        animationSpeed: 0.5,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        handDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        numbersMultipleOf90: 'text-black font-black text-4xl',
        numbersMultipleOf30: 'text-white font-extrabold text-lg',
        numbersMultipleOf10: 'text-white font-thin text-lg',
        dotsMultipleOf90: 'w-4 h-4 mt-2 bg-black',
        dotsMultipleOf30: 'w-2 h-2 mt-4 bg-black ',
        dotsMultipleOf10: 'w-1 h-1 mt-4 bg-black',
      },
      {
        context: {
          currentTime: new Date(1356091200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "180° est le véritable midi",
        descriptionText: 'Lorsque le soleil est au zénith',
        animationSpeed: 2,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        numbersMultipleOf90: 'text-black font-black text-4xl',
        numbersMultipleOf30: 'text-white font-extrabold text-lg',
        numbersMultipleOf10: 'text-white font-thin text-lg',
        dotsMultipleOf90: 'w-4 h-4 mt-2 bg-black',
        dotsMultipleOf30: 'w-2 h-2 mt-4 bg-slate-200 ',
        dotsMultipleOf10: 'w-2 h-2 mt-4 bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1356134399000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "0° marque le vrai milieu de la nuit",
        descriptionText: "Lorsque le soleil est de l'autre côté de la Terre",
        animationSpeed: 2,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        numbersMultipleOf90: 'text-black font-black text-4xl',
        numbersMultipleOf30: 'text-white font-extrabold text-lg',
        numbersMultipleOf10: 'text-white font-thin text-lg',
        dotsMultipleOf90: 'w-4 h-4 mt-2 bg-black',
        dotsMultipleOf30: 'w-2 h-2 mt-4 bg-slate-200 ',
        dotsMultipleOf10: 'w-2 h-2 mt-4 bg-slate-100',
        hand: 'text-slate-800',
      },
      {
        context: {
          currentTime: new Date(1356134400000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Les moustaches représentent le jour et la nuit",
        descriptionText: "En fonction de la saison et de la latitude",
        animationSpeed: 0.4,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        titleDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        handDisplay: false,
        mustachesEquinox: 'text-black',
        mustachesSummerSunrise: 'text-black',
        mustachesWinterSunrise: 'text-black',
        mustachesWinterSunset: 'text-black',
        mustachesSummerSunset: 'text-black',
      },
      {
        context: {
          currentTime: new Date(1340252400000 + 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'été...",
        descriptionText: "Le soleil se lève par ici",
        animationSpeed: 1.2,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        dayNightBlurDisplay: false,
        mustachesEquinox: 'text-slate-400',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1340307600000 - 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'été...",
        descriptionText: "Puis se couche par là",
        animationSpeed: 2,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        dayNightBlurDisplay: true,
        mustachesEquinox: 'text-slate-400',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1356161400000 + 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'hiver...",
        descriptionText: "Le soleil se lève ici",
        animationSpeed: 1,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        dayNightBlurDisplay: true,
        mustachesEquinox: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1356193800000 - 1000*60*20),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Au solstice d'hiver...",
        descriptionText: "Et se couche par là",
        animationSpeed: 2,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        dayNightBlurDisplay: true,
        mustachesEquinox: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesWinterSunrise: 'text-nt-yellow-dark',
        mustachesWinterSunset: 'text-nt-yellow-dark',
        mustachesSummerSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Les jours d'équinoxes",
        descriptionText: "La durée du jour est égale à celle de la nuit",
        animationSpeed: .4,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: true,
        dayNightBlurDisplay: false,
        mustachesEquinox: 'text-nt-yellow-dark',
        mustachesWinterSunrise: 'text-slate-400',
        mustachesSummerSunrise: 'text-slate-400',
        mustachesSummerSunset: 'text-slate-400',
        mustachesWinterSunset: 'text-slate-400',
      },
      {
        context: {
          currentTime: new Date(1332331200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Tutoriel terminé !",
        descriptionText: "Pour continuer, l'application a besoin de configurer une position géographique",
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        sunDisplay: true,
        dayNightBlurDisplay: true,
      }
    ]
  }
}