export const spiralSkins = {
  full: {
    default: {
      animationSpeed: .4,
      spiralShowDaysNumber: true,
      spiralShowTitle: true,
    },
    hideDaysNumber: {
      spiralShowDaysNumber: false,
    },
    hideTitle: {
      spiralShowTitle: false,
    },
    welcome: {
      context: {
        currentTime: new Date(new Date().setUTCHours(10, 0, 0, 0)),
        latitude: 42.42,
        longitude: 0,
      },
      animationSpeed: .5,
      descriptionText: "Découvrir la Spirale des 13 lunes, calendrier universel 100% basé sur la nature",
    },
    tutorial: [
      {
        context: {
          currentTime: new Date(1355999200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: 'Je suis une horloge naturelle',
        descriptionText: "Je pointe à chaque instant en direction du soleil",
        animationSpeed: .8,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon unique aiguille",
        descriptionText: 'Tourne lentement, une seule fois par jour',
        animationSpeed: 8,
        mustachesDisplay: false,
        dotsDisplay: false,
        numbersDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
      },
      {
        context: {
          currentTime: new Date(1356099900000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "Mon cadran est gradué en 360°",
        descriptionText: 'Bye bye les 24 heures 60 minutes et 60 secondes',
        animationSpeed: 0.5,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        handDisplay: false,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: false,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        numbersMultipleOf90: 'text-black font-black text-4xl',
        numbersMultipleOf30: 'text-white font-extrabold text-lg',
        numbersMultipleOf10: 'text-white font-thin text-lg',
        dotsMultipleOf90: 'w-4 h-4 mt-2 bg-black',
        dotsMultipleOf30: 'w-2 h-2 mt-4 bg-black ',
        dotsMultipleOf10: 'w-1 h-1 mt-4 bg-black',
      },
      {
        context: {
          currentTime: new Date(1356091200000),
          latitude: 42.42,
          longitude: 0,
        },
        titleText: "180° est le véritable midi",
        descriptionText: 'Lorsque le soleil est au zénith',
        animationSpeed: 2,
        mustachesDisplay: false,
        dotsDisplay: true,
        numbersDisplay: true,
        moonDisplay: false,
        ntzDisplay: false,
        sunDisplay: true,
        dayNightRingDisplay: false,
        dayNightBlurDisplay: false,
        numbersMultipleOf90: 'text-black font-black text-4xl',
        numbersMultipleOf30: 'text-white font-extrabold text-lg',
        numbersMultipleOf10: 'text-white font-thin text-lg',
        dotsMultipleOf90: 'w-4 h-4 mt-2 bg-black',
        dotsMultipleOf30: 'w-2 h-2 mt-4 bg-slate-200 ',
        dotsMultipleOf10: 'w-2 h-2 mt-4 bg-slate-100',
        hand: 'text-slate-800',
      }
    ]
  }
}